http://localhost:3000/

### return login and check cookie
http://localhost:3000/auth/

###
POST http://localhost:3000/auth/register/
content-type: application/json

{
    "firstName": "bea",
    "lastName": "triz",
    "email": "beatriz@gmail.com",
    "newpassword": "123456",
    "passwordConfirm": "123456"
}

###  login
POST http://localhost:3000/auth/login/
content-type: application/json

{
    "email": "rjrosa@gmail.com",
    "password": "123456"
}

###  logout/clear cookie
GET  http://localhost:3000/auth/logout/

### update
POST http://localhost:3000/auth/updateSelf/
content-type: application/json

{
    "firstName": "roberto",
    "lastName": "rosa",
    "password": "123456"

}
### update with password
POST http://localhost:3000/auth/updateSelf/
content-type: application/json

{
    "firstName": "cina",
    "lastName": "bon",
    "password": "123456",
    "newPassword": "654321",
    "confirmNewPassword":"6543210"
    
}
